apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-chat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: chat
        image: chat-app
        imagePullPolicy: Never
        
---
apiVersion: v1
kind: Service
metadata:
  name: chat-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
